apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-cluster
  namespace: gitops-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/exarep/gitops-cluster-hub.git
    targetRevision: main
    path: resources/gitops-cluster
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
