apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openshift-gitops-operator.yaml   # sync-wave-0
  - gitops-cluster.yaml              # sync-wave-1
  - openshift-nmstate.yaml           # sync-wave-2
  - console-notification.yaml        # sync-wave-3
  - open-cluster-management.yaml     # sync-wave-4
  - openshift-pipelines.yaml         # sync-wave-5
