apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-pipelines
  namespace: gitops-cluster
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/exarep/gitops-cluster-hub.git
    targetRevision: main
    path: resources/openshift-pipelines
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
