apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: exarep-gitops-cluster-argocd-cluster-admin
  annotations:
    argocd.argoproj.io/sync-wave: "3"
subjects:
  - kind: ServiceAccount
    name: exarep-gitops-cluster-argocd-argocd-application-controller
    namespace: exarep-gitops-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
