apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secrets-manager-credentials
            namespace: openshift-external-secrets-operator
            key: access-key
          secretAccessKeySecretRef:
            name: aws-secrets-manager-credentials
            namespace: openshift-external-secrets-operator
            key: secret-access-key